### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by justbrowsing37** [SophieCodingg/bombparty-helpbot#2]
Can you make a contributer to this repo? I have the driver file with time optimizations and better error handling. I want to send the files into this so can you help we with that?

I copied the code to a seperate file and names it Optimized-Driver.py but i havent tested it,
Im gonna be out of country for a while so i was wondering is you can test it for me after making me a contributer

Thanks

**Comment by justbrowsing37** [comment]
Sorry about so many issues of the bat, but im on vacation and i need somehting to keep myself busy so i ws wondering if i could get ur contact, be it phone number of whatever, ill try and log on to ds tm and dm you. ALso what time zone do you live in, just so i know when to not bother you bc you might be sleeping or whatever. Sorry again for so much

**Comment by AgustinCoding** [comment]
Hey man, you did an awesome job rigth there!. Accept the invitation to be part of the repository
